[erp1 erp2 erpsub time sig] = pop_comperp( ALLEEG, 1, [1] ,[] ,'addavg','on',...
    'addstd','off','subavg','off','diffavg','off','diffstd','off','chans',[1:70] ,...
    'ylim', [-20 20],'tplotopt',{'ydir' 1 'colors', {{'k' 'linewidth' 2},{'k--' 'linewidth' 2}}});
%save figure in matlab fig format