function createfigure(cdata1, X1, Y1, cdata2, X2, YMatrix1, Y2, X3, YMatrix2, cdata3, X4, Y3, Y4, X5, YMatrix3, VertexNormals1, ZData1, YData1, XData1, Vertices1, Faces1, X6, Y5, Z1, XMatrix1, Y6, Z2, X7, Y7, Z3)
%CREATEFIGURE(CDATA1,X1,Y1,CDATA2,X2,YMATRIX1,Y2,X3,YMATRIX2,CDATA3,X4,Y3,Y4,X5,YMATRIX3,VERTEXNORMALS1,ZDATA1,YDATA1,XDATA1,VERTICES1,FACES1,X6,Y5,Z1,XMATRIX1,Y6,Z2,X7,Y7,Z3)
%  CDATA1:  image cdata
%  X1:  vector of x data
%  Y1:  vector of y data
%  CDATA2:  image cdata
%  X2:  vector of x data
%  YMATRIX1:  matrix of y data
%  Y2:  vector of y data
%  X3:  vector of x data
%  YMATRIX2:  matrix of y data
%  CDATA3:  image cdata
%  X4:  vector of x data
%  Y3:  vector of y data
%  Y4:  vector of y data
%  X5:  vector of x data
%  YMATRIX3:  matrix of y data
%  VERTEXNORMALS1:  patch vertexnormals
%  ZDATA1:  patch zdata
%  YDATA1:  patch ydata
%  XDATA1:  patch xdata
%  VERTICES1:  patch vertices
%  FACES1:  patch faces
%  X6:  vector of x data
%  Y5:  vector of y data
%  Z1:  vector of z data
%  XMATRIX1:  matrix of x data
%  Y6:  vector of y data
%  Z2:  vector of z data
%  X7:  vector of x data
%  Y7:  vector of y data
%  Z3:  vector of z data

%  Auto-generated by MATLAB on 13-Jun-2012 13:20:23

% Create figure
figure1 = figure('Color',[0.93 0.96 1]);
colormap('jet');

% Create axes
axes('Visible','off','Parent',figure1);

% Create axes
axes1 = axes('Parent',figure1,'Tag','itc','YTickLabel','',...
    'YTick',zeros(1,0),...
    'XTickLabel','',...
    'XTick',zeros(1,0),...
    'Position',[0.2075 0.6561 0.62 0.269],...
    'Layer','top',...
    'CLim',[-0.3076 0.3076]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim([13.41 986.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim([9.889 52.11]);
box('on');
hold('all');

% Create image
image([15.84 19.75 23.66 29.53 33.45 39.31 43.23 49.09 53.01 58.87 62.79 68.66 72.57 78.44 82.35 88.22 92.13 98 101.9 107.8 111.7 117.6 121.5 127.3 131.3 137.1 141 146.9 150.8 156.7 160.6 166.5 170.4 176.2 180.2 186 189.9 195.8 199.7 205.6 209.5 213.4 219.3 223.2 229.1 233 238.8 242.7 248.6 252.5 258.4 262.3 268.2 272.1 278 281.9 287.7 291.7 297.5 301.4 307.3 311.2 317.1 321 326.9 330.8 336.6 340.6 346.4 350.3 356.2 360.1 366 369.9 375.8 379.7 385.5 389.5 395.3 399.2 403.2 409 412.9 418.8 422.7 428.6 432.5 438.4 442.3 448.1 452.1 457.9 461.8 467.7 471.6 477.5 481.4 487.3 491.2 497 501 506.8 510.7 516.6 520.5 526.4 530.3 536.2 540.1 545.9 549.9 555.7 559.6 565.5 569.4 575.3 579.2 585.1 589 594.8 598.8 602.7 608.5 612.5 618.3 622.2 628.1 632 637.9 641.8 647.7 651.6 657.4 661.4 667.2 671.1 677 680.9 686.8 690.7 696.6 700.5 706.3 710.3 716.1 720 725.9 729.8 735.7 739.6 745.5 749.4 755.3 759.2 765 768.9 774.8 778.7 784.6 788.5 792.4 798.3 802.2 808.1 812 817.8 821.8 827.6 831.5 837.4 841.3 847.2 851.1 857 860.9 866.7 870.7 876.5 880.4 886.3 890.2 896.1 900 905.9 909.8 915.7 919.6 925.4 929.3 935.2 939.1 945 948.9 954.8 958.7 964.6 968.5 974.3 978.2 984.1],...
    [12 16.22 20.44 24.67 28.89 33.11 37.33 41.56 45.78 50],cdata1,...
    'Parent',axes1,...
    'CDataMapping','scaled');

% Create plot
plot(X1,Y1,'Parent',axes1,'LineWidth',2,'LineStyle','--','Color',[1 0 1]);

% Create axes
axes2 = axes('Parent',figure1,'Tag','cbar','YAxisLocation','right',...
    'XTickLabel','',...
    'Position',[0.8662 0.6561 0.03875 0.269],...
    'Layer','top');
% Uncomment the following line to preserve the X-limits of the axes
% xlim([-1 2]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim([-0.3088 0.3088]);
box('on');
hold('all');

% Create image
image([0 1],[-0.3076 0.3076],cdata2,'Parent',axes2);

% Create title
title('ERSP(dB)');

% Create axes
axes3 = axes('Parent',figure1,'YTick',[-0.5 0.5],'YAxisLocation','right',...
    'TickLength',[0.02 0.025],...
    'Position',[0.2075 0.5746 0.62 0.0815]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim([15.84 984.1]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim([-0.6868 0.8202]);
box('on');
hold('all');

% Create multiple lines using matrix input to plot
plot(X2,YMatrix1,'Parent',axes3,'LineWidth',2);

% Create plot
plot(X1,Y2,'Parent',axes3,'LineWidth',2,'LineStyle','--','Color',[1 0 1]);

% Create xlabel
xlabel('Time (ms)');

% Create ylabel
ylabel('dB','VerticalAlignment','cap');

% Create axes
axes4 = axes('Parent',figure1,'XDir','reverse','TickLength',[0.02 0.025],...
    'Position',[0.13 0.6561 0.0775 0.269]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim([12 50]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim([27.18 73.96]);
view([90 90]);
box('on');
hold('all');

% Create multiple lines using matrix input to plot
plot1 = plot(X3,YMatrix2,'Parent',axes4,'LineWidth',2);
set(plot1(2),'Color',[0 1 0]);
set(plot1(3),'Color',[0 1 0]);
set(plot1(4),'LineStyle',':','Color',[0 0 0]);
set(plot1(5),'LineStyle',':','Color',[0 0 0]);

% Create xlabel
xlabel('Frequency (Hz)','VerticalAlignment','bottom','Rotation',90,...
    'HorizontalAlignment','center');

% Create ylabel
ylabel('dB','VerticalAlignment','cap','HorizontalAlignment','center');

% Create axes
axes5 = axes('Parent',figure1,'YTickLabel','','YTick',zeros(1,0),...
    'XTickLabel','',...
    'XTick',zeros(1,0),...
    'Position',[0.2075 0.1915 0.62 0.269],...
    'Layer','top',...
    'CLim',[-0.343 0.343]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim([13.41 986.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim([9.889 52.11]);
box('on');
hold('all');

% Create image
image([15.84 19.75 23.66 29.53 33.45 39.31 43.23 49.09 53.01 58.87 62.79 68.66 72.57 78.44 82.35 88.22 92.13 98 101.9 107.8 111.7 117.6 121.5 127.3 131.3 137.1 141 146.9 150.8 156.7 160.6 166.5 170.4 176.2 180.2 186 189.9 195.8 199.7 205.6 209.5 213.4 219.3 223.2 229.1 233 238.8 242.7 248.6 252.5 258.4 262.3 268.2 272.1 278 281.9 287.7 291.7 297.5 301.4 307.3 311.2 317.1 321 326.9 330.8 336.6 340.6 346.4 350.3 356.2 360.1 366 369.9 375.8 379.7 385.5 389.5 395.3 399.2 403.2 409 412.9 418.8 422.7 428.6 432.5 438.4 442.3 448.1 452.1 457.9 461.8 467.7 471.6 477.5 481.4 487.3 491.2 497 501 506.8 510.7 516.6 520.5 526.4 530.3 536.2 540.1 545.9 549.9 555.7 559.6 565.5 569.4 575.3 579.2 585.1 589 594.8 598.8 602.7 608.5 612.5 618.3 622.2 628.1 632 637.9 641.8 647.7 651.6 657.4 661.4 667.2 671.1 677 680.9 686.8 690.7 696.6 700.5 706.3 710.3 716.1 720 725.9 729.8 735.7 739.6 745.5 749.4 755.3 759.2 765 768.9 774.8 778.7 784.6 788.5 792.4 798.3 802.2 808.1 812 817.8 821.8 827.6 831.5 837.4 841.3 847.2 851.1 857 860.9 866.7 870.7 876.5 880.4 886.3 890.2 896.1 900 905.9 909.8 915.7 919.6 925.4 929.3 935.2 939.1 945 948.9 954.8 958.7 964.6 968.5 974.3 978.2 984.1],...
    [12 16.22 20.44 24.67 28.89 33.11 37.33 41.56 45.78 50],cdata3,...
    'Parent',axes5,...
    'CDataMapping','scaled');

% Create plot
plot(X1,Y1,'Parent',axes5,'LineWidth',2,'LineStyle','--','Color',[1 0 1]);

% Create axes
axes6 = axes('Parent',figure1,'Tag','cbar','YAxisLocation','right',...
    'XTickLabel','',...
    'Position',[0.8662 0.1915 0.03875 0.269],...
    'Layer','top');
% Uncomment the following line to preserve the X-limits of the axes
% xlim([-1 2]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim([0 0.343]);
box('on');
hold('all');

% Create image
image([0 1],[-0.343 0.343],cdata2,'Parent',axes6);

% Create title
title('ITC');

% Create axes
axes7 = axes('Parent',figure1,'YTick',[0 10],'YAxisLocation','right',...
    'TickLength',[0.02 0.025],...
    'Position',[0.2075 0.11 0.62 0.0815]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim([15.84 984.1]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim([-4.415 10.96]);
box('on');
hold('all');

% Create plot
plot(X4,Y3,'Parent',axes7,'LineWidth',2);

% Create plot
plot(X1,Y4,'Parent',axes7,'LineWidth',2,'LineStyle','--','Color',[1 0 1]);

% Create plot
plot(X5,X1,'Parent',axes7,'Color',[0 0 0]);

% Create xlabel
xlabel('Time (ms)');

% Create ylabel
ylabel('\muV','VerticalAlignment','cap');

% Create axes
axes8 = axes('Parent',figure1,'YTick',[0 0.08],'XDir','reverse',...
    'Position',[0.13 0.1915 0.0775 0.269]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim([12 50]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim([-0.00634 0.08997]);
view([90 90]);
box('on');
hold('all');

% Create multiple lines using matrix input to plot
plot2 = plot(X3,YMatrix3,'Parent',axes8,'LineWidth',2);
set(plot2(2),'Color',[0 1 0]);
set(plot2(3),'LineStyle',':','Color',[0 0 0]);

% Create xlabel
xlabel('Frequency (Hz)','VerticalAlignment','bottom','Rotation',90,...
    'HorizontalAlignment','center');

% Create ylabel
ylabel('ERP','VerticalAlignment','cap','HorizontalAlignment','center');

% Create axes
axes9 = axes('Visible','off','Parent',figure1,...
    'Position',[0.0525 0.4604 0.155 0.1141],...
    'PlotBoxAspectRatio',[1 1 1]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim([-0.525 0.525]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim([-0.525 0.525]);
hold('all');

% Create patch
patch('Parent',axes9,'VertexNormals',VertexNormals1,'ZData',ZData1,...
    'YData',YData1,...
    'XData',XData1,...
    'Vertices',Vertices1,...
    'Faces',Faces1);

% Create plot3
plot3(X6,Y5,Z1,'Parent',axes9,'LineWidth',1.7,'Color',[0 0 0]);

% Create multiple lines using matrix input to plot3
plot3(XMatrix1,Y6,Z2,'Parent',axes9,'LineWidth',1.7,'Color',[0 0 0]);

% Create plot3
plot3(X7,Y7,Z3,'Parent',axes9,'MarkerSize',10,'Marker','.',...
    'LineStyle','none',...
    'Color',[1 0 0]);

